---
driver:
  name: vagrant
  network:
    - ['private_network', { ip: '192.168.0.20' }]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04-LTS
    driver:
      box: ubuntu-12.04-LTS
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[cartodb::default]
    attributes:
